language: ruby
rvm:
  - 2.3.4
  - 2.4.1
before_install: gem install bundler
cache: bundler
sudo: false
fast_finish: true
env:
  - SKIP_INTEGRATION=true
notifications:
  email:
    on_success: always
    on_failure: always
